---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/rajinpkn/dev.rajindustries.org
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp rts.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH